## Выполнение практического задания № 2
### Урок 2. Видеоурок. Вычисления с помощью Numpy. Работа с данными в Pandas

#### Тема “Вычисления с помощью Numpy”
*Задание 1*  <br>
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк
и 2 столбцов.  <br>
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6,
8, 11, 10, 7. <br>
Будем считать, что каждый столбец - это признак, а строка - наблюдение. <br>
Затем найдите среднее значение по каждому признаку, используя метод mean массива
Numpy. <br>
Результат запишите в массив mean_a, в нем должно быть 2 элемента. <br>

In [70]:
import numpy as np

In [71]:
col_1 = [1, 2, 3, 3, 1]
col_2 = [6, 8, 11, 10, 7]

In [72]:
a = np.column_stack([col_1, col_2])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [73]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

*Задание 2*  <br>
Вычислите массив a_centered, отняв от значений массива “а” средние значения  <br>
соответствующих признаков, содержащиеся в массиве mean_a. <br>
Вычисление должно производиться в одно действие. <br>
Получившийся массив должен иметь размер 5x2. <br>

In [74]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

*Задание 3*  <br>
Найдите скалярное произведение столбцов массива a_centered. <br>
В результате должна получиться величина a_centered_sp. <br>
Затем поделите a_centered_sp на N-1, где N - число наблюдений. <br>

In [75]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [76]:
print(np.divide(a_centered_sp, a_centered.shape[0] - 1))

2.0


*Задание 4***  <br>
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”.  <br>
В задании 3 мы делили сумму произведений центрированных признаков на N-1, а не на N,  <br>
поэтому полученная нами величина является несмещенной оценкой ковариации. <br>
Подробнее узнать о ковариации можно здесь: "[Выборочная ковариация и выборочная дисперсия — Студопедия](https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html)" <br>
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. <br>
В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”.  <br>
В получившейся ковариационной матрице (массив Numpy размером 2x2)  <br>
искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [77]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

In [78]:
np.cov(a.T)[0][1]

2.0

#### Тема “Работа с данными в Pandas”
*Задание 1*  <br>
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. <br>
Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно <br>
содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский']. <br>
Затем создайте датафрейм books cо столбцами author_id, book_title и price, <br>
в которых соответственно содержатся данные: <br>
[1, 1, 1, 2, 2, 3, 3], <br>
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'] <br>
Нужны prices! <br>
[500, 400, 300, 350, 450, 600, 200]

In [79]:
import pandas as pd

In [80]:
authors_dict = {'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']}
authors = pd.DataFrame(authors_dict)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [81]:
books_dict = {'author_id': [1, 1, 1, 2, 2, 3, 3],
             'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
             'price': [500, 400, 300, 350, 450, 600, 200]}
books = pd.DataFrame(book_dict)
books

author_id            book_title  price
0          1           Отцы и дети    500
1          1                 Рудин    400
2          1     Дворянское гнездо    300
3          2      Толстый и тонкий    350
4          2       Дама с собачкой    450
5          3                 Гроза    600
6          3  Таланты и поклонники    200

*Задание 2*  <br>
Получите датафрейм authors_price, соединив дата фреймы authors и books по полю author_id.

In [82]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    500
1          1    Тургенев                 Рудин    400
2          1    Тургенев     Дворянское гнездо    300
3          2       Чехов      Толстый и тонкий    350
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    600
6          3  Островский  Таланты и поклонники    200

*Задание 3*  <br>
Создайте датафрейм top5, в котором содержатся строки из authors_price <br>
с пятью самыми дорогими книгами.

In [83]:
# Способ 1
top5 = authors_price.sort_values(by = 'price', ascending = False)[:5]
top5

author_id author_name        book_title  price
5          3  Островский             Гроза    600
0          1    Тургенев       Отцы и дети    500
4          2       Чехов   Дама с собачкой    450
1          1    Тургенев             Рудин    400
3          2       Чехов  Толстый и тонкий    350

In [84]:
# Способ 2
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name        book_title  price
5          3  Островский             Гроза    600
0          1    Тургенев       Отцы и дети    500
4          2       Чехов   Дама с собачкой    450
1          1    Тургенев             Рудин    400
3          2       Чехов  Толстый и тонкий    350

*Задание 4*  <br>
Создайте датафрейм authors_stat на основе информации из authors_price. <br>
В датафрейме authors_stat должны быть четыре столбца: <br>
author_name, min_price, max_price и mean_price, <br>
в которых должны содержаться соответственно <br>
имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [104]:
authors_stat = pd.DataFrame({'min_price': authors_price.groupby('author_name')['price'].min(),
                             'max_price': authors_price.groupby('author_name')['price'].max(),
                             'mean_price': authors_price.groupby('author_name')['price'].mean()})
authors_stat.reset_index()
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         200        600       400.0
Тургенев           300        500       400.0
Чехов              350        450       400.0

*Задание 5***  <br>
Создайте новый столбец в датафрейме authors_price под названием cover, <br>
в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. <br>
В этот столбец поместите данные из следующего списка: <br>
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']. <br>
Просмотрите документацию по функции pd.pivot table с помощью вопросительного знака. <br>
Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. <br>
Используйте для этого функцию pd.pivot_table. <br>
При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. <br>
Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy. <br>
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". <br>
Затем загрузите из этого файла датафрейм и назовите его book_info2. <br>
Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [105]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    500  твердая
1          1    Тургенев                 Рудин    400   мягкая
2          1    Тургенев     Дворянское гнездо    300   мягкая
3          2       Чехов      Толстый и тонкий    350  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    600   мягкая
6          3  Островский  Таланты и поклонники    200   мягкая

In [114]:
book_info = pd.pivot_table(authors_price, index = 'author_name', columns = 'cover', values = 'price', aggfunc = np.sum)
book_info

<ipython-input-114-10ad48ffd21d>:1: FutureWarning: The provided callable <function sum at 0x78bd80c8add0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  book_info = pd.pivot_table(authors_price, index = 'author_name', columns = 'cover', values = 'price', aggfunc = np.sum)


cover        мягкая  твердая
author_name                 
Островский    800.0      NaN
Тургенев      700.0    500.0
Чехов           NaN    800.0

In [116]:
book_info = book_info.fillna(value = 0)
book_info

cover        мягкая  твердая
author_name                 
Островский    800.0      0.0
Тургенев      700.0    500.0
Чехов           0.0    800.0

In [117]:
book_info.to_pickle('book_info.pkl')
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский    800.0      0.0
Тургенев      700.0    500.0
Чехов           0.0    800.0